
[sounds]

	[sounds.mobs]
		disable_enderman_sounds = false
		disable_dragon_sounds = false
		disable_slime_sounds = false
		disable_wither_sounds = false
		disable_bat_sounds = false

	[sounds.blocks]
		disable_fire_sounds = false
		disable_primed_tnt_sounds = false
		disable_explosion_sounds = false

	[sounds.players]
		disable_mystery_box_sounds = false
		disable_levelup_sounds = false
		disable_delivery_man_sounds = false
		disable_stepping_sounds = false

	[sounds.tile_entities]
		disable_item_pickup_sounds = false
		disable_experience_orb_sounds = false
		disable_arrow_sounds = false
		disable_firework_sounds = false

